apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: stvkcgmwl-go 
  janus-idp.io/tekton: stvkcgmwl-go
  backstage.io/kubernetes-id: stvkcgmwl-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: stvkcgmwl-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml